apiVersion: v1
kind: Secret
metadata:
  name: jinja-config
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
  template.jinja: {{ .Files.Get "files/template.jinja" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.secretName }}
  namespace: dev
type: Opaque
data:
  {{- range .Values.container.env.secret }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}